export enum STEP {
  CROP = 0,
  FILTERS = 1,
  PUBLICATION = 2,
  PUBLICATION_COMPLETED = 3,
}

export enum STEPS {
  SELECT_IMAGE = 1,
  CROP = 2,
  FILTERS = 3,
  PUBLICATION = 4,
  PUBLICATION_COMPLETED = 5,
}
